# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        uses: hesgang/UpdateAliyunFC@main
        with:
          access_key_id: ${{ secrets.ACCESS_KEY_ID }}
          access_key_secret: ${{ secrets.ACCESS_KEY_SECRET }}
          account_ID: ${{ secrets.ACCOUNT_ID }}
          server_name: ${{ secrets.SERVER_NAME }}
          function_name: ${{ secrets.FUNCTION_NAME }}
          region: ${{ secrets.REGION }}
           
